### PR TITLE
Fix 0.4 deprecated bindings

### PR DESCRIPTION
**Pull request by yuyichao**
Also Fix test and rename tests.jl to runtests.jl.

### CODE REVIEW

**Comment by yuyichao** [comment]
Could someone enable travis CI for this repo? @Keno ?

**Comment by yuyichao** [comment]
Ping. @Keno

**Comment by Keno** [comment]
Sorry!

**Comment by yuyichao** [comment]
Wow. that's a extremely fast response to my pinging.........

**Pull request merged**
