### PR TITLE
Bugfix in polyder

### LINKED ISSUE #80: Bug in polyder
### Description

Right now the only check in the package is `T<:Number`. Hence, we have `NaN`s and `Inf`s resulting in weird behaviours. One example was in #78, where the polynomial evaluation was wrong.

We also have a strange behaviour when taking the derivatives.

### Observed Behaviour

```julia
julia> using Polynomials
julia> p = Poly([NaN, 1, Inf])
Poly(NaN + 1.0⋅x + Inf⋅x^2)
julia> p'
Poly(1.0 + Inf⋅x)
julia> p''
Poly(Inf)
julia> p'''
Poly(0.0)
julia> polyder(polyint(p))
Poly(NaN + 1.0⋅x + Inf⋅x^2)
julia> polyint(polyder(p))
Poly(1.0⋅x + Inf⋅x^2)
```

### Desired Behaviour

If the package continues to support `NaN`s and `Inf`s, I believe any operation on `NaN`s should produce `NaN`, including the derivative. Right now, derivative of `p(x) = NaN` is `0.0`. Similarly, when `p(x) = Inf`, the derivative evaluates to `0.0`, again. However, when we apply the definition (at any point), we get `(Inf-Inf)/h`. Numerator, there, is also `NaN`. I assume, derivative of `Inf` should yield `NaN`, instead.

So, my proposed solution is at least as follows:

```julia
julia> using Polynomials
julia> p = Poly([NaN, 1, Inf])
Poly(NaN + 1.0⋅x + Inf⋅x^2)
julia> p'
Poly(NaN + Inf⋅x)
julia> p''
Poly(NaN)
julia> p'''
Poly(NaN)
julia> polyder(polyint(p))
Poly(NaN + 1.0⋅x + Inf⋅x^2)
julia> polyint(polyder(p))
Poly(NaN⋅x + Inf⋅x^2)
```

What do you think? Am I missing something?

**Note.** A PR will follow.

### PR DESCRIPTION
**Pull request by aytekinar**
Closes #80.

### CODE REVIEW

**Comment by jverzani** [comment]
Should we address the NaN issue more generally that this does, as mentioned in the issue? It seems like we should while this is being done.

**Comment by aytekinar** [comment]
do you mean we should check in `polyder`, `polyint` and `polyval`with `any(isnan(p.a))` and always return `Poly(T[NaN], p.var)`?

**Comment by jverzani** [comment]
Yes.

**Comment by aytekinar** [comment]
Will follow with a new PR.. Allow me 10 minutes please...

**Pull request closed without merging**
