### PR TITLE
Polyint

### PR DESCRIPTION
**Pull request by jverzani**
Add definite integral interface to polyint, as mentioned in #110 .

### CODE REVIEW

**Comment by stevengj** [comment]
LGTM.

Note that the docstring formatting here is nonstandard for Julia.  If you follow the format of Base, it would be, for example:
```
"""
    polyint(p::Poly, k::Number=0)

Indefinite integral of a polynomial: integrate the polynomial `p` term
by term, optionally adding constant term `k`. The degree of the
resulting polynomial is one higher than the degree of `p`.


Examples:
```
polyint(Poly([1, 0, -1]))      # Poly(x - 0.3333333333333333x^3)
polyint(Poly([1, 0, -1]), 2)  # Poly(2.0 + x - 0.3333333333333333x^3)
```
See also `polyint(p, a, b)` for a definite integral over `[a,b]`.
"""
```

**Comment by stevengj** [comment]
In principle, you could probably write a recurrence for `P(b) - P(a)` in terms of `b-a`, but I'm not sure it's worth it here.

**Comment by jverzani** [comment]
Thanks for your help! I'll leave this as is. I'll open a separate issue about updating docstrings.

**Comment by stevengj** [comment]
Basically, one would want to work out the polynomial `P(x + δ)` in `δ = b - a`.   See: http://math.stackexchange.com/questions/694565/polynomial-shift

**Pull request merged**
